export const actionTypes = {
	ADD_TO_FAVOURITE: "ADD_TO_FAVOURITE",
	REMOVE_FROM_FAVOURITE: "REMOVE_FROM_FAVOURITE",
	REMOVE_ALL_FAVOURITE: "REMOVE_ALL_FAVOURITE",
	GET_ALL_FAVOURITE: "GET_ALL_FAVOURITE",
};
